"""Sphinx configuration for the Yin documentation site.

The C API reference is pulled from the Doxygen XML (generated by ``doxygen
Doxyfile`` into ``_doxygen/xml``) via the Breathe extension.
"""
import os

# -- Project information -----------------------------------------------------
project = "Yin"
author = "Jingren Wang"
copyright = "Yin"
release = "1.0"

# -- General configuration ---------------------------------------------------
extensions = [
    "breathe",
]

# Render cross-references for the C domain by default.
primary_domain = "c"
highlight_language = "c"

# -- Breathe / Doxygen bridge ------------------------------------------------
# XML is produced by `doxygen Doxyfile` (see Doxyfile: OUTPUT_DIRECTORY/_xml).
breathe_projects = {"yin": os.path.join(os.path.dirname(__file__), "_doxygen", "xml")}
breathe_default_project = "yin"
# Pull members (functions, typedefs, enums) into group pages automatically.
breathe_default_members = ("members",)

# -- HTML output -------------------------------------------------------------
html_theme = "furo"
html_static_path = ["_static"]
